-- Portable ANSI SQL (works unmodified on H2 and Postgres).
-- `code` is nullable: generated codes insert transiently-null, then get set in the
-- same transaction once the id is known (see UrlService.shorten()).
CREATE TABLE url_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10),
    long_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    disabled_at TIMESTAMP,
    click_count BIGINT NOT NULL DEFAULT 0,
    last_clicked_at TIMESTAMP,
    CONSTRAINT uq_url_mapping_code UNIQUE (code)
);
